version: 2
defaults:
  config: "latest.json"
instances:
  - user: "binance_04"
    long_mode: "gs"
    symbols:
     - "HIFIUSDT"
     - "TONUSDT"
     - "NEARUSDT"
     - "ACHUSDT"
     - "INJUSDT"
     - "RUNEUSDT"
     - "STMXUSDT"
     - "ZENUSDT"
     - "MOVRUSDT"
     - "FRONTUSDT"
     - "ZRXUSDT"
     - "SSVUSDT"
     - "JOEUSDT"
     - "IOTXUSDT"
     - "XVGUSDT"
     - "BELUSDT"
     - "RADUSDT"
     - "REEFUSDT"
     - "BAKEUSDT"
     - "OGNUSDT"


  - user: "binance_04"
    long_mode: "gs"
    symbols:
     - "SPELLUSDT"
     - "CELOUSDT"
     - "IOTAUSDT"
     - "QNTUSDT"
     - "CAKEUSDT"
     - "JUPUSDT"
     - "DOGEUSDT"
     - "1000SHIBUSDT"
     - "1000XECUSDT"
     - "1000LUNCUSDT"
     - "1000PEPEUSDT"
     - "1000BONKUSDT"
     - "1000SATSUSDT"
     - "1000RATSUSDT"
     - "ARPAUSDT"