version: 2
defaults:
  config: "latest.json"
instances:
  - user: "binance_04"
    long_mode: "n"
    symbols:
     - "REEFUSDT"
     - "RUNEUSDT"
     - "PEOPLEUSDT"

  - user: "binance_04"
    long_mode: "gs"
    symbols:
     - "DARUSDT"
     - "LQTYUSDT"
     - "BELUSDT"
     - "BAKEUSDT"
     - "ATAUSDT"
     - "IOTXUSDT"
     - "PHBUSDT"
     - "DENTUSDT"
     - "CELOUSDT"
     - "1000XECUSDT"
     - "NKNUSDT"
     - "RSRUSDT"
     - "FTMUSDT"
     - "NEARUSDT"
     - "OCEANUSDT"
     - "DEFIUSDT"
     - "CTSIUSDT"
     - "MINAUSDT"
     - "ANKRUSDT"
     - "C98USDT"
     - "QTUMUSDT"
     - "GMTUSDT"