version: 2
defaults:
  config: "latest.json"
instances:
  - user: "binance_04"
    long_mode: "n"
    symbols:
     - "1000PEPEUSDT"
     - "AEVOUSDT"
     - "AXLUSDT"
     - "GLMUSDT"
     - "MAVIAUSDT"
     - "METISUSDT"
     - "MYROUSDT"
     - "OMUSDT"
     - "ORDIUSDT"
     - "PIXELUSDT"
     - "PORTALUSDT"
     - "STRKUSDT"
     - "TONUSDT"
     - "VANRYUSDT"
     - "1000SHIBUSDT"

    #  - "WAVESUSDT"
     - "WIFUSDT"
    #  - "RSRUSDT"
     - "FRONTUSDT"
     - "ZRXUSDT"
    #  - "1000BONKUSDT"
    #  - "CAKEUSDT"
     - "JUPUSDT"
     - "RSRUSDT"
     - "LRCUSDT"
    #  - "MEMEUSDT"
     - "DOGEUSDT"
    #  - "JTOUSDT"    
    #  - "INJUSDT"
    #  - "ZILUSDT"
    #  - "HIFIUSDT"    
    #  - "ZENUSDT"
    #  - "RUNEUSDT"
    #  - "QNTUSDT"
    #  - "RONINUSDT"
    #  - "APEUSDT"
    #  - "ACHUSDT"
    #  - "KSMUSDT"
    #  - "BELUSDT"
    #  - "LOOMUSDT"
    #  - "BAKEUSDT"


  - user: "binance_04"
    long_mode: "gs"
    symbols:
    #  - "ALGOUSDT"
     - "ARBUSDT"
     - "STMXUSDT"
    #  - "ARPAUSDT"
    #  - "CELOUSDT"
     - "CHRUSDT"
    #  - "DUSKUSDT"
    #  - "GLMRUSDT"
    #  - "HOTUSDT"
     - "IOTXUSDT"
    #  - "MOVRUSDT"
     - "SPELLUSDT"  
    #  - "SSVUSDT" 
     - "XVGUSDT"

    #  - "1000SATSUSDT"
    #  - "NEARUSDT"
    #  - "OGNUSDT"
    #  - "DARUSDT"
    #  - "JOEUSDT"
    #  - "KEYUSDT"
    #  - "STMXUSDT" 