version: 2
defaults:
  config: "latest.json"
instances:
  - user: "binance_04"
    long_mode: "gs"
    symbols:
     - "HIFIUSDT"
     - "WEAVESUSDT"
     - "SSVUSDT"
     - "ZENUSDT"
     - "JOEUSDT"
     - "TONUSDT"
     - "RUNEUSDT"
     - "WIFUSDT"
     - "ARPAUSDT"
     - "QNTUSDT"
     - "ZILUSDT"
     - "DUSKUSDT"
     - "MOVRUSDT"
     - "GLMRUSDT"
     - "RONINUSDT"
     - "APEUSDT"
     - "ALGOUSDT"
     - "CHRUSDT"
     - "ACHUSDT"
     - "KSMUSDT"
     - "BELUSDT"
     - "DARUSDT"
     - "ARBUSDT"
     - "FRONTUSDT"
     - "KEYUSDT"
     - "LOOMUSDT"
     - "INJUSDT"
     - "1000PEPEUSDT"
     - "NEARUSDT"
     - "BAKEUSDT"
     - "HOTUSDT"


  - user: "binance_04"
    long_mode: "gs"
    symbols:
     - "SPELLUSDT"
     - "CELOUSDT"
     - "1000SATSUSDT"
     - "RADUSDT"     
     - "STMXUSDT"
     - "IOTXUSDT"
     - "XVGUSDT"
     - "OGNUSDT"