version: 2
defaults:
  config: "latest.json"
instances:
  - user: "binance_04"
    long_mode: "n"
    symbols:
     - "1000PEPEUSDT"
     - "ARBUSDT"
     - "ARPAUSDT"
     - "CHRUSDT"
     - "DARUSDT"
     - "DUSKUSDT"
     - "GLMRUSDT"
     - "INJUSDT"
     - "MOVRUSDT"
     - "NEARUSDT"
     - "ZILUSDT"
     - "JOEUSDT"
     - "WIFUSDT"
     - "HIFIUSDT"
     - "WAVESUSDT"
     - "SSVUSDT"
     - "TONUSDT"
     - "ALGOUSDT"
     - "FRONTUSDT"
     - "KEYUSDT"
     - "HOTUSDT"
    
    #  - "ZENUSDT"
    #  - "RUNEUSDT"
    #  - "QNTUSDT"
    #  - "RONINUSDT"
    #  - "APEUSDT"
    #  - "ACHUSDT"
    #  - "KSMUSDT"
    #  - "BELUSDT"
    #  - "LOOMUSDT"
    #  - "BAKEUSDT"


  - user: "binance_04"
    long_mode: "gs"
    symbols:
    #  - "1000SATSUSDT"
    #  - "CELOUSDT"
    #  - "IOTXUSDT"
    #  - "OGNUSDT"
    #  - "SPELLUSDT"   
    #  - "STMXUSDT" 
    #  - "XVGUSDT"