version: 2
defaults:
  config: "latest.json"
instances:
  - user: "binance_04"
    long_mode: "n"
    symbols:
     - "1000PEPEUSDT"
     - "AEVOUSDT"
     - "AXLUSDT"
     - "GLMUSDT"
     - "MAVIAUSDT"
     - "METISUSDT"
     - "MYROUSDT"
     - "OMUSDT"
     - "ORDIUSDT"
     - "PIXELUSDT"
     - "PORTALUSDT"
     - "STRKUSDT"
     - "TONUSDT"
     - "VANRYUSDT"

     - "WAVESUSDT"
     - "WIFUSDT"
     - "RSRUSDT"
     - "SSVUSDT"
     - "FRONTUSDT"
     - "ZRXUSDT"
     - "CAKEUSDT"
     - "JUPUSDT"
     - "LRCUSDT"
     - "JTOUSDT"

    
    #  - "INJUSDT"
    #  - "ZILUSDT"
    #  - "HIFIUSDT"    
    #  - "ZENUSDT"
    #  - "RUNEUSDT"
    #  - "QNTUSDT"
    #  - "RONINUSDT"
    #  - "APEUSDT"
    #  - "ACHUSDT"
    #  - "KSMUSDT"
    #  - "BELUSDT"
    #  - "LOOMUSDT"
    #  - "BAKEUSDT"


  - user: "binance_04"
    long_mode: "gs"
    symbols:
    #  - "1000SATSUSDT"
     - "CELOUSDT"
     - "IOTXUSDT"
     - "NEARUSDT"
    #  - "OGNUSDT"
     - "SPELLUSDT"   
     - "DARUSDT"
     - "JOEUSDT"
     - "KEYUSDT"
     - "GLMRUSDT"
     - "CHRUSDT"
     - "ALGOUSDT"
     - "ARPAUSDT"
     - "HOTUSDT"
     - "ARBUSDT"
     - "MOVRUSDT"
    #  - "STMXUSDT" 
     - "XVGUSDT"
     - "DUSKUSDT"